### ISSUE TITLE
next.config.js file

### ISSUE THREAD

**Issue by AntjeNotteboom** [AntjeNotteboom/MaakHetPersoonlijk#4]
https://github.com/AntjeNotteboom/MaakHetPersoonlijk/blob/150980d0945cd08f15798fab05b905a935214a41/client/next.config.js 

Ik heb besloten om met Contentful te werken als database en had eerst mijn api keys in een .env file gestoken. Hier luisterde mijn code niet naar dus heb dit dan in een next.config.js file gezet, maar die wordt nu ook naar github gedeployed. Zet ik die dan gewoon best in mijn .gitignore of is er een andere manier?

**Comment by SimonVanherweghe** [comment]
Contentful: prima
api keys in next.config: niet doen, deze moeten in de .env file, nergens anders

Hangt er nu van af waarom jouw code 'niet luisterde'.
Belangrijk om te melden is dat jouw communicatie met contentful **serverside** moet gebeuren. Anders gooi je jouw api tokens te grabbel en kan iedereen met jouw database foefelen. Sowieso de namen van de env variabelen **niet prefixen** met NEXT_PUBLIC, dan zijn ze enkel serverside beschikbaar.
Wil je vanuit jouw client/frontend contentful aanspreken, dan kan je dit doen via een eigen API die je in Next aanmaak (zoals we met de buttondown integratie gedaan hebben)

Merk ook op dat Contentful 2 API's heeft (nog meer dan dat zelf, maar doet er hier niet toe) Eentje om uit te lezen en eentje om content aan te maken/aan te passen. (Content delivery & Content management)
https://www.contentful.com/developers/docs/references/
Als je de beide in één file wil aanspreken, dan kan je dit als volgt doen:
```
import { createClient as deliveryClient } from "contentful";
import { createClient as managementClient } from "contentful-management";
```

Het is handiger/properder om alle functionaliteit van contentful samen in één file te steken. Ergens onder `services/data.js` of zo. Daarin export je dan functies in de zin van `getMessageById`, `getAllMessages`, `createMessage` etc...
In jouw getStaticProps/Paths en in jouw API routes kan je dan deze functies gebruiken.
